# <center>Frozen Lake
### <center>Using Q-learning to not die

<center>
S F F F <br>
F H F H <br>
F F F H <br>
H F F G <br>
</center>

S = starting position<br>
F = frozen, or safe<br>
H = hole, or death<br>
G = goal<br>

<img src='frozenlake.png'>

First, let's import all the necessary libraries. 

In [1]:
import gym
import numpy as np
import time
from IPython.display import clear_output
import pandas as pd

Next, let's watch some random playing of the game.

In [2]:
env = gym.make("FrozenLake-v0", is_slippery=False)
for game in range(10):
    state = env.reset()
    for t in range(100):
        clear_output(wait=True)
        env.render()
        time.sleep(0.2)
        action = env.action_space.sample()
        next_state, reward, done, info = env.step(action)
        if done:
            break

  (Left)
SFFF
FHFH
FFFH
HFFG


### <center>Discuss
#### <center> What do you observe from watching the random agent? 
#### <center> Do you think this will be an easy environment to solve?

Now, let's try using Q-learning to train an agent to play the game.

We will start with a version of FrozenLake where the surface is not slippery. This is a deterministic environment -  every action we choose to take will always move us in that direction.

You will need the following elements:
- <b>Q-table</b>:
    - Instantiate a table of zeros of size (number of states)x(number of actions)
    - You can use np.zeros() to create the array.
    
- <b>Gamma</b>:
    - The discount factor for future rewards.
    - Typically a number close to 1 (0.95-0.99) but feel free to try different values.
- <b>Scores array</b>:
    - An empty list to append scores from each game to.
    - Also, set a running score variable to zero at the start of each game.
- <b>Action selection</b>:
    - At each step, choose the best action.
    - Since at the beginning, our table will be all zeros, we need to be able to choose an action at random if more than one has the highest Q-value.
    - You can use np.max() to get the highest Q-value.
    - Then get the action for each of those highest Q-values with np.where(). (Note: np.where() returns a tuple where the first element is the array of actions.)
    - Then use np.random.choice() to select one of the best actions.
- <b>Q-value calculation</b>:
    - Using the Q-formula:
    <img src='q_formula.png'>
    - You will have to find the maximum Q-value at the next state.
    - You will want to set the appropriate value in your Q-table to this.
- <b>Reward tracking</b>:
    - Add the current reward to the running score total
    - After each game, store the game score in the scores list
- <b>State transition</b>
    - Set the next state as the current state.
- <b>Termination</b>
    - If the agent managed to not fall in a hole and thus made it to the goal for 10 episodes in a row, then the environment is considered solved.

In [21]:
env = gym.make("FrozenLake-v0", is_slippery=False)

Q_table = np.zeros([env.observation_space.n, env.action_space.n])
gamma = 0.99
scores = []

## We will play for a maximum of 10000 games.
for episode in range(10000):
    state = env.reset()
    score = 0
    done = False

    while not done:
        clear_output(wait=True)
        env.render()
        action = np.random.choice(np.where(Q_table[state,:]==np.max(Q_table[state,:]))[0])
            
        next_state, reward, done, info = env.step(action)
        
        Q_value = reward + (gamma * np.max(Q_table[next_state, :]))
        
        Q_table[state, action] = Q_value
        
        score += reward
        
        state = next_state
        
    scores.append(score)
    
    
    ## If we have played at least 10 games, check if the last 10 games resulted in success
    if episode>9:
        if np.mean(scores[-10:])==1:
            print("Solved!")
            print("Average per past 100 games: " + str(np.mean(scores[-100:])))
            print("Number of games played: " + str(episode))
            break
            
if np.mean(scores[-10:])!=1:
    print('Failed')
env.close()

  (Right)
SFFF
FHFH
FFFH
HFFG
Solved!
Average per past 100 games: 0.16304347826086957
Number of games played: 91


Take a look at your Q-table now.

In [22]:
q_table_not_slippery = np.round(Q_table,3)
q_table_not_slippery

array([[0.   , 0.951, 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.961, 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.97 , 0.   ],
       [0.   , 0.98 , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.99 , 0.   ],
       [0.   , 0.   , 1.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   ]])

### <center>Discuss
#### <center> How did your agent do? 
#### <center> What does your Q-table look like?

Now we are going to try a stochastic version of our environment by setting is_slippery to true. There is a now a chance that we will slide on the ice and move a different direction than what we chose. 

### <center>Discuss
#### <center> How do you think the challenge will change in the new, slippery version of the environment?


Copy your code from above and paste below with the following changes:
- <b>is_slippery</b>:
    - Set to True

In [25]:
env = gym.make("FrozenLake-v0", is_slippery=True)

Q_table = np.zeros([env.observation_space.n, env.action_space.n])
gamma = 0.99
scores = []

## We will play for a maximum of 10000 games.
for episode in range(10000):
    state = env.reset()
    score = 0
    done = False

    while not done:
        clear_output(wait=True)
        env.render()
        action = np.random.choice(np.where(Q_table[state,:]==np.max(Q_table[state,:]))[0])
            
        next_state, reward, done, info = env.step(action)
        
        Q_value = reward + (gamma * np.max(Q_table[next_state, :]))
        
        Q_table[state, action] = Q_value
        
        score += reward
        
        state = next_state
        
    scores.append(score)
    
    
    ## If we have played at least 10 games, check if the last 10 games resulted in success
    if episode>9:
        if np.mean(scores[-10:])==1:
            print("Solved!")
            print("Average per past 100 games: " + str(np.mean(scores[-100:])))
            print("Number of games played: " + str(episode))
            break
            
if np.mean(scores[-10:])!=1:
    print('Failed')
env.close()

  (Left)
SFFF
FHFH
FFFH
HFFG
Failed


Take a look at your Q-table now.

In [24]:
q_table_is_slippery = np.round(Q_table,3)
q_table_is_slippery

array([[0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   ],
       [0.99 , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.97 , 0.   ],
       [0.   , 0.886, 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   ]])

### <center>Discuss
#### <center> How did your agent perform in the slippery environment?
#### <center> Why is performance different in this environment?


## <center>Solution

#### <center>Greedy epsilon policy
<center>Makes the agent explore the environment more at first and then later on relying only on its knowledge.

#### <center>Learning rate
<center>Allows the agent to accumulate knowledge, not just overriding previous Q-values with each new experience.

<center>Q[s, a] = Q[s, a] + alpha*(R + gamma*Max[Q(s’, A)] - Q[s, a])

In [26]:
env = gym.make("FrozenLake-v0", is_slippery=True)

Q_table = np.zeros([env.observation_space.n, env.action_space.n])
gamma = 0.95
scores = []

epsilon = 1
epsilon_decay = 0.995
epsilon_min = 0.01
alpha = 0.85

for episode in range(10000):
    state = env.reset()
    score = 0
    done = False
    while not done:
        if np.random.rand() < epsilon:
            action = env.action_space.sample()
        else:
            action = np.random.choice(np.where(Q_table[state,:]==np.max(Q_table[state,:]))[0])
        next_state, reward, done, info = env.step(action)
        Q_value = reward + gamma * np.max(Q_table[next_state, :])
        Q_table[state, action] = Q_table[state, action] + alpha*(Q_value-Q_table[state,action])
        score += reward
        state = next_state     
    scores.append(score)
    epsilon = epsilon*epsilon_decay
    if episode>99:
        if np.mean(scores[-10:])==1:
            print("Solved!")
            print("Average per past 10 games: " + str(np.mean(scores[-10:])))
            print("Number of games played: " + str(episode))
            break
     
    if episode%100==0:
        print('Average success rate: ', np.mean(scores), ' Epsilon: ', epsilon)
if np.mean(scores[-10:])!=1:
    print('Failed')
env.close()

Average success rate:  0.0  Epsilon:  0.995
Average success rate:  0.009900990099009901  Epsilon:  0.6027415843082742
Average success rate:  0.01990049751243781  Epsilon:  0.36512303261753626
Average success rate:  0.026578073089700997  Epsilon:  0.2211807388415433
Average success rate:  0.04239401496259352  Epsilon:  0.13398475271138335
Average success rate:  0.05788423153692615  Epsilon:  0.0811640021330769
Average success rate:  0.09484193011647254  Epsilon:  0.04916675299948831
Average success rate:  0.1355206847360913  Epsilon:  0.029783765425331846
Average success rate:  0.1647940074906367  Epsilon:  0.018042124582040707
Average success rate:  0.19644839067702552  Epsilon:  0.010929385683282892
Average success rate:  0.23276723276723277  Epsilon:  0.0066206987359377885
Solved!
Average per past 10 games: 1.0
Number of games played: 1002


In [27]:
q_table_is_slippery_solved = np.round(Q_table,3)
q_table_is_slippery_solved

array([[0.484, 0.04 , 0.031, 0.015],
       [0.005, 0.017, 0.002, 0.184],
       [0.002, 0.009, 0.006, 0.156],
       [0.002, 0.   , 0.002, 0.026],
       [0.587, 0.01 , 0.032, 0.069],
       [0.   , 0.   , 0.   , 0.   ],
       [0.098, 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   ],
       [0.023, 0.022, 0.027, 0.678],
       [0.009, 0.583, 0.053, 0.012],
       [0.9  , 0.003, 0.002, 0.001],
       [0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   ],
       [0.08 , 0.021, 0.806, 0.096],
       [0.246, 0.983, 0.258, 0.198],
       [0.   , 0.   , 0.   , 0.   ]])